---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: k8s-app-a
  namespace: prod
  labels:
    app: k8s-app-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-app-a
  template:
    metadata:
      labels:
        app: k8s-app-a
    spec:
      containers:
      - name: k8s-app-a
        image: "rajaninandu/app-argocd:24"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-app-a
  namespace: prod
spec:
  selector:
    app: k8s-app-a
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 80
