apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  namespace: app
spec:
  selector:
    matchLabels:
      app: canary
  replicas: 2
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
      - name: canary
        image: "rajaninandu/app:10"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: canary-app
  namespace: app
spec:
  selector:
    app: canary
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 32001
